### ISSUE TITLE
weex debug 不能调试某一个页面

### ISSUE THREAD

**Issue by eeolqy** [karynsong/weex-eros#1]
你们的微信群不能通过扫码进群了

**Comment by karynsong** [comment]
您好，您那边加入微信群了么？

**Comment by eeolqy** [comment]
没有 你们扫码界面提示群满了 
我的微信号：13161672105
 
 
------------------ Original ------------------

**Comment by PerseveranceZ** [comment]
目前 安卓 ios 的 weex debug 已经支持
