### ISSUE TITLE
hello world 失败

### ISSUE THREAD

**Issue by Rem486** [karynsong/weex-eros#2]
env: 
   **node -v**
   v8.9.1
   **eros -v**
   eros-cli:
   The following instructions are provided to help you build app !
   [eros] · current version: 2.0.0-beta.5

why: 打开方式不对

how: 
https://github.com/bmfe/eros-template/wiki/%E4%B8%9A%E5%8A%A1%E5%BC%80%E5%8F%91
  按照文档介绍，
  eros init 
  npm install
  eros install
  编写hello world，
  eros dev
启动服务   Webserver started at http://localhost:52077

desc:
![image](https://user-images.githubusercontent.com/22462424/33158507-6eac342a-d045-11e7-8515-d7855ff5b398.png)

只有这个目录树

**Comment by karynsong** [comment]
我们目前只支持 iOS 和 android 的开发，这个起的只是 js 的服务，需要在客户端的环境下运行。目前文档和项目已经迁移到 https://github.com/bmfe

**Comment by Rem486** [comment]
嗯好的，谢谢
